{
  "regions": ["hnd1"],
  "functions": {
    "api/*.php": {
      "runtime": "vercel-php@0.5.4"
    }
  },
  "routes": [
    { "src": "/(.*)", "dest": "/$1" },
    { "handle": "filesystem" },
    { "src": "/.*", "dest": "api/login.php" }
  ]
}